// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: agents.sql

package dbsqlc

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createAgent = `-- name: CreateAgent :one
INSERT INTO agents (org_id, name, hostname, tags, token_hash, signing_key_hash)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, org_id, name, hostname, tags, frozen, revoked, rotation_required, expires_at, last_seen_at, created_at
`

type CreateAgentParams struct {
	OrgID          uuid.UUID `json:"org_id"`
	Name           string    `json:"name"`
	Hostname       string    `json:"hostname"`
	Tags           []byte    `json:"tags"`
	TokenHash      string    `json:"token_hash"`
	SigningKeyHash string    `json:"signing_key_hash"`
}

type CreateAgentRow struct {
	ID               uuid.UUID   `json:"id"`
	OrgID            uuid.UUID   `json:"org_id"`
	Name             string      `json:"name"`
	Hostname         string      `json:"hostname"`
	Tags             []byte      `json:"tags"`
	Frozen           bool        `json:"frozen"`
	Revoked          bool        `json:"revoked"`
	RotationRequired bool        `json:"rotation_required"`
	ExpiresAt        time.Time   `json:"expires_at"`
	LastSeenAt       **time.Time `json:"last_seen_at"`
	CreatedAt        time.Time   `json:"created_at"`
}

func (q *Queries) CreateAgent(ctx context.Context, arg CreateAgentParams) (CreateAgentRow, error) {
	row := q.db.QueryRow(ctx, createAgent,
		arg.OrgID,
		arg.Name,
		arg.Hostname,
		arg.Tags,
		arg.TokenHash,
		arg.SigningKeyHash,
	)
	var i CreateAgentRow
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Name,
		&i.Hostname,
		&i.Tags,
		&i.Frozen,
		&i.Revoked,
		&i.RotationRequired,
		&i.ExpiresAt,
		&i.LastSeenAt,
		&i.CreatedAt,
	)
	return i, err
}

const deleteAgent = `-- name: DeleteAgent :exec
DELETE FROM agents WHERE id = $1 AND org_id = $2
`

type DeleteAgentParams struct {
	ID    uuid.UUID `json:"id"`
	OrgID uuid.UUID `json:"org_id"`
}

func (q *Queries) DeleteAgent(ctx context.Context, arg DeleteAgentParams) error {
	_, err := q.db.Exec(ctx, deleteAgent, arg.ID, arg.OrgID)
	return err
}

const freezeAgent = `-- name: FreezeAgent :exec
UPDATE agents SET frozen = true WHERE id = $1
`

func (q *Queries) FreezeAgent(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, freezeAgent, id)
	return err
}

const getAgentByID = `-- name: GetAgentByID :one
SELECT id, org_id, name, hostname, tags, frozen, revoked, rotation_required, expires_at, last_seen_at, created_at
FROM agents WHERE id = $1 AND org_id = $2 LIMIT 1
`

type GetAgentByIDParams struct {
	ID    uuid.UUID `json:"id"`
	OrgID uuid.UUID `json:"org_id"`
}

type GetAgentByIDRow struct {
	ID               uuid.UUID   `json:"id"`
	OrgID            uuid.UUID   `json:"org_id"`
	Name             string      `json:"name"`
	Hostname         string      `json:"hostname"`
	Tags             []byte      `json:"tags"`
	Frozen           bool        `json:"frozen"`
	Revoked          bool        `json:"revoked"`
	RotationRequired bool        `json:"rotation_required"`
	ExpiresAt        time.Time   `json:"expires_at"`
	LastSeenAt       **time.Time `json:"last_seen_at"`
	CreatedAt        time.Time   `json:"created_at"`
}

func (q *Queries) GetAgentByID(ctx context.Context, arg GetAgentByIDParams) (GetAgentByIDRow, error) {
	row := q.db.QueryRow(ctx, getAgentByID, arg.ID, arg.OrgID)
	var i GetAgentByIDRow
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Name,
		&i.Hostname,
		&i.Tags,
		&i.Frozen,
		&i.Revoked,
		&i.RotationRequired,
		&i.ExpiresAt,
		&i.LastSeenAt,
		&i.CreatedAt,
	)
	return i, err
}

const getAgentByTokenHash = `-- name: GetAgentByTokenHash :one
SELECT id, org_id, signing_key_hash, fingerprint_hash, fingerprint_drift, frozen, revoked, rotation_required, expires_at
FROM agents WHERE token_hash = $1 LIMIT 1
`

type GetAgentByTokenHashRow struct {
	ID               uuid.UUID `json:"id"`
	OrgID            uuid.UUID `json:"org_id"`
	SigningKeyHash   string    `json:"signing_key_hash"`
	FingerprintHash  *string   `json:"fingerprint_hash"`
	FingerprintDrift bool      `json:"fingerprint_drift"`
	Frozen           bool      `json:"frozen"`
	Revoked          bool      `json:"revoked"`
	RotationRequired bool      `json:"rotation_required"`
	ExpiresAt        time.Time `json:"expires_at"`
}

func (q *Queries) GetAgentByTokenHash(ctx context.Context, tokenHash string) (GetAgentByTokenHashRow, error) {
	row := q.db.QueryRow(ctx, getAgentByTokenHash, tokenHash)
	var i GetAgentByTokenHashRow
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.SigningKeyHash,
		&i.FingerprintHash,
		&i.FingerprintDrift,
		&i.Frozen,
		&i.Revoked,
		&i.RotationRequired,
		&i.ExpiresAt,
	)
	return i, err
}

const rotateAgentToken = `-- name: RotateAgentToken :exec
UPDATE agents SET token_hash = $2, signing_key_hash = $3, rotation_required = false WHERE id = $1
`

func (q *Queries) RotateAgentToken(ctx context.Context, id uuid.UUID, tokenHash, signingKeyHash string) error {
	_, err := q.db.Exec(ctx, rotateAgentToken, id, tokenHash, signingKeyHash)
	return err
}

const listAgentsByOrgID = `-- name: ListAgentsByOrgID :many
SELECT id, name, hostname, tags, frozen, revoked, rotation_required, expires_at, last_seen_at, created_at
FROM agents WHERE org_id = $1 ORDER BY created_at DESC
`

type ListAgentsByOrgIDRow struct {
	ID               uuid.UUID   `json:"id"`
	Name             string      `json:"name"`
	Hostname         string      `json:"hostname"`
	Tags             []byte      `json:"tags"`
	Frozen           bool        `json:"frozen"`
	Revoked          bool        `json:"revoked"`
	RotationRequired bool        `json:"rotation_required"`
	ExpiresAt        time.Time   `json:"expires_at"`
	LastSeenAt       **time.Time `json:"last_seen_at"`
	CreatedAt        time.Time   `json:"created_at"`
}

func (q *Queries) ListAgentsByOrgID(ctx context.Context, orgID uuid.UUID) ([]ListAgentsByOrgIDRow, error) {
	rows, err := q.db.Query(ctx, listAgentsByOrgID, orgID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAgentsByOrgIDRow
	for rows.Next() {
		var i ListAgentsByOrgIDRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Hostname,
			&i.Tags,
			&i.Frozen,
			&i.Revoked,
			&i.RotationRequired,
			&i.ExpiresAt,
			&i.LastSeenAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeAgent = `-- name: RevokeAgent :exec
UPDATE agents SET revoked = true WHERE id = $1 AND org_id = $2
`

type RevokeAgentParams struct {
	ID    uuid.UUID `json:"id"`
	OrgID uuid.UUID `json:"org_id"`
}

func (q *Queries) RevokeAgent(ctx context.Context, arg RevokeAgentParams) error {
	_, err := q.db.Exec(ctx, revokeAgent, arg.ID, arg.OrgID)
	return err
}

const setFingerprintDrift = `-- name: SetFingerprintDrift :exec
UPDATE agents SET fingerprint_drift = true WHERE id = $1
`

func (q *Queries) SetFingerprintDrift(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, setFingerprintDrift, id)
	return err
}

const setFingerprintHash = `-- name: SetFingerprintHash :exec
UPDATE agents SET fingerprint_hash = $2 WHERE id = $1
`

type SetFingerprintHashParams struct {
	ID              uuid.UUID `json:"id"`
	FingerprintHash *string   `json:"fingerprint_hash"`
}

func (q *Queries) SetFingerprintHash(ctx context.Context, arg SetFingerprintHashParams) error {
	_, err := q.db.Exec(ctx, setFingerprintHash, arg.ID, arg.FingerprintHash)
	return err
}

const updateAgentLastSeen = `-- name: UpdateAgentLastSeen :exec
UPDATE agents SET last_seen_at = now() WHERE id = $1
`

func (q *Queries) UpdateAgentLastSeen(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, updateAgentLastSeen, id)
	return err
}
