// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: alerts.sql

package dbsqlc

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createAlertRule = `-- name: CreateAlertRule :one
INSERT INTO alert_rules (org_id, name, target, condition, severity, notification_channels)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, org_id, name, target, condition, severity, notification_channels, enabled, created_at, updated_at
`

type CreateAlertRuleParams struct {
	OrgID                uuid.UUID     `json:"org_id"`
	Name                 string        `json:"name"`
	Target               AlertTarget   `json:"target"`
	Condition            []byte        `json:"condition"`
	Severity             AlertSeverity `json:"severity"`
	NotificationChannels []byte        `json:"notification_channels"`
}

type CreateAlertRuleRow struct {
	ID                   uuid.UUID     `json:"id"`
	OrgID                uuid.UUID     `json:"org_id"`
	Name                 string        `json:"name"`
	Target               AlertTarget   `json:"target"`
	Condition            []byte        `json:"condition"`
	Severity             AlertSeverity `json:"severity"`
	NotificationChannels []byte        `json:"notification_channels"`
	Enabled              bool          `json:"enabled"`
	CreatedAt            time.Time     `json:"created_at"`
	UpdatedAt            time.Time     `json:"updated_at"`
}

func (q *Queries) CreateAlertRule(ctx context.Context, arg CreateAlertRuleParams) (CreateAlertRuleRow, error) {
	row := q.db.QueryRow(ctx, createAlertRule,
		arg.OrgID,
		arg.Name,
		arg.Target,
		arg.Condition,
		arg.Severity,
		arg.NotificationChannels,
	)
	var i CreateAlertRuleRow
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Name,
		&i.Target,
		&i.Condition,
		&i.Severity,
		&i.NotificationChannels,
		&i.Enabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteAlertRule = `-- name: DeleteAlertRule :exec
DELETE FROM alert_rules WHERE id = $1 AND org_id = $2
`

type DeleteAlertRuleParams struct {
	ID    uuid.UUID `json:"id"`
	OrgID uuid.UUID `json:"org_id"`
}

func (q *Queries) DeleteAlertRule(ctx context.Context, arg DeleteAlertRuleParams) error {
	_, err := q.db.Exec(ctx, deleteAlertRule, arg.ID, arg.OrgID)
	return err
}

const getAlertRule = `-- name: GetAlertRule :one
SELECT id, org_id, name, target, condition, severity, notification_channels, enabled, created_at, updated_at
FROM alert_rules WHERE id = $1 AND org_id = $2 LIMIT 1
`

type GetAlertRuleParams struct {
	ID    uuid.UUID `json:"id"`
	OrgID uuid.UUID `json:"org_id"`
}

type GetAlertRuleRow struct {
	ID                   uuid.UUID     `json:"id"`
	OrgID                uuid.UUID     `json:"org_id"`
	Name                 string        `json:"name"`
	Target               AlertTarget   `json:"target"`
	Condition            []byte        `json:"condition"`
	Severity             AlertSeverity `json:"severity"`
	NotificationChannels []byte        `json:"notification_channels"`
	Enabled              bool          `json:"enabled"`
	CreatedAt            time.Time     `json:"created_at"`
	UpdatedAt            time.Time     `json:"updated_at"`
}

func (q *Queries) GetAlertRule(ctx context.Context, arg GetAlertRuleParams) (GetAlertRuleRow, error) {
	row := q.db.QueryRow(ctx, getAlertRule, arg.ID, arg.OrgID)
	var i GetAlertRuleRow
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Name,
		&i.Target,
		&i.Condition,
		&i.Severity,
		&i.NotificationChannels,
		&i.Enabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listAlertEvents = `-- name: ListAlertEvents :many
SELECT id, rule_id, agent_id, fired_at, resolved_at, value_at_fire, status
FROM alert_events WHERE rule_id = $1 ORDER BY fired_at DESC LIMIT $2
`

type ListAlertEventsParams struct {
	RuleID uuid.UUID `json:"rule_id"`
	Limit  int32     `json:"limit"`
}

func (q *Queries) ListAlertEvents(ctx context.Context, arg ListAlertEventsParams) ([]AlertEvent, error) {
	rows, err := q.db.Query(ctx, listAlertEvents, arg.RuleID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AlertEvent
	for rows.Next() {
		var i AlertEvent
		if err := rows.Scan(
			&i.ID,
			&i.RuleID,
			&i.AgentID,
			&i.FiredAt,
			&i.ResolvedAt,
			&i.ValueAtFire,
			&i.Status,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAlertRules = `-- name: ListAlertRules :many
SELECT id, name, target, severity, enabled, created_at, updated_at
FROM alert_rules WHERE org_id = $1 ORDER BY created_at DESC
`

type ListAlertRulesRow struct {
	ID        uuid.UUID     `json:"id"`
	Name      string        `json:"name"`
	Target    AlertTarget   `json:"target"`
	Severity  AlertSeverity `json:"severity"`
	Enabled   bool          `json:"enabled"`
	CreatedAt time.Time     `json:"created_at"`
	UpdatedAt time.Time     `json:"updated_at"`
}

func (q *Queries) ListAlertRules(ctx context.Context, orgID uuid.UUID) ([]ListAlertRulesRow, error) {
	rows, err := q.db.Query(ctx, listAlertRules, orgID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAlertRulesRow
	for rows.Next() {
		var i ListAlertRulesRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Target,
			&i.Severity,
			&i.Enabled,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFiringEvents = `-- name: ListFiringEvents :many
SELECT ae.id, ae.rule_id, ae.agent_id, ae.fired_at, ae.status
FROM alert_events ae
JOIN alert_rules ar ON ar.id = ae.rule_id
WHERE ar.org_id = $1 AND ae.status = 'firing'
ORDER BY ae.fired_at DESC
LIMIT $2
`

type ListFiringEventsParams struct {
	OrgID uuid.UUID `json:"org_id"`
	Limit int32     `json:"limit"`
}

type ListFiringEventsRow struct {
	ID      uuid.UUID        `json:"id"`
	RuleID  uuid.UUID        `json:"rule_id"`
	AgentID uuid.UUID        `json:"agent_id"`
	FiredAt time.Time        `json:"fired_at"`
	Status  AlertEventStatus `json:"status"`
}

func (q *Queries) ListFiringEvents(ctx context.Context, arg ListFiringEventsParams) ([]ListFiringEventsRow, error) {
	rows, err := q.db.Query(ctx, listFiringEvents, arg.OrgID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListFiringEventsRow
	for rows.Next() {
		var i ListFiringEventsRow
		if err := rows.Scan(
			&i.ID,
			&i.RuleID,
			&i.AgentID,
			&i.FiredAt,
			&i.Status,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const resolveAlertEvent = `-- name: ResolveAlertEvent :exec
UPDATE alert_events SET resolved_at = now(), status = 'resolved' WHERE id = $1
`

func (q *Queries) ResolveAlertEvent(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, resolveAlertEvent, id)
	return err
}

const updateAlertRule = `-- name: UpdateAlertRule :one
UPDATE alert_rules
SET name = $3, condition = $4, severity = $5, notification_channels = $6, enabled = $7, updated_at = now()
WHERE id = $1 AND org_id = $2
RETURNING id, org_id, name, target, condition, severity, notification_channels, enabled, created_at, updated_at
`

type UpdateAlertRuleParams struct {
	ID                   uuid.UUID     `json:"id"`
	OrgID                uuid.UUID     `json:"org_id"`
	Name                 string        `json:"name"`
	Condition            []byte        `json:"condition"`
	Severity             AlertSeverity `json:"severity"`
	NotificationChannels []byte        `json:"notification_channels"`
	Enabled              bool          `json:"enabled"`
}

type UpdateAlertRuleRow struct {
	ID                   uuid.UUID     `json:"id"`
	OrgID                uuid.UUID     `json:"org_id"`
	Name                 string        `json:"name"`
	Target               AlertTarget   `json:"target"`
	Condition            []byte        `json:"condition"`
	Severity             AlertSeverity `json:"severity"`
	NotificationChannels []byte        `json:"notification_channels"`
	Enabled              bool          `json:"enabled"`
	CreatedAt            time.Time     `json:"created_at"`
	UpdatedAt            time.Time     `json:"updated_at"`
}

func (q *Queries) UpdateAlertRule(ctx context.Context, arg UpdateAlertRuleParams) (UpdateAlertRuleRow, error) {
	row := q.db.QueryRow(ctx, updateAlertRule,
		arg.ID,
		arg.OrgID,
		arg.Name,
		arg.Condition,
		arg.Severity,
		arg.NotificationChannels,
		arg.Enabled,
	)
	var i UpdateAlertRuleRow
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Name,
		&i.Target,
		&i.Condition,
		&i.Severity,
		&i.NotificationChannels,
		&i.Enabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
