// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: logs.sql

package dbsqlc

import (
	"context"
	"time"

	"github.com/google/uuid"
)

type IngestLogEntriesParams struct {
	AgentID   uuid.UUID `json:"agent_id"`
	Source    string    `json:"source"`
	Level     string    `json:"level"`
	Message   string    `json:"message"`
	Count     int32     `json:"count"`
	FirstSeen time.Time `json:"first_seen"`
	LastSeen  time.Time `json:"last_seen"`
}

const queryLogEntries = `-- name: QueryLogEntries :many
SELECT agent_id, source, level, message, count, first_seen, last_seen, received_at
FROM log_entries
WHERE agent_id = $1
  AND received_at >= $2
  AND received_at < $3
  AND ($5::text IS NULL OR level = $5)
ORDER BY received_at DESC
LIMIT $4
`

type QueryLogEntriesParams struct {
	AgentID      uuid.UUID `json:"agent_id"`
	ReceivedAt   time.Time `json:"received_at"`
	ReceivedAt_2 time.Time `json:"received_at_2"`
	Limit        int32     `json:"limit"`
	Level        *string   `json:"level"`
}

type QueryLogEntriesRow struct {
	AgentID    uuid.UUID `json:"agent_id"`
	Source     string    `json:"source"`
	Level      string    `json:"level"`
	Message    string    `json:"message"`
	Count      int32     `json:"count"`
	FirstSeen  time.Time `json:"first_seen"`
	LastSeen   time.Time `json:"last_seen"`
	ReceivedAt time.Time `json:"received_at"`
}

func (q *Queries) QueryLogEntries(ctx context.Context, arg QueryLogEntriesParams) ([]QueryLogEntriesRow, error) {
	rows, err := q.db.Query(ctx, queryLogEntries,
		arg.AgentID,
		arg.ReceivedAt,
		arg.ReceivedAt_2,
		arg.Limit,
		arg.Level,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []QueryLogEntriesRow
	for rows.Next() {
		var i QueryLogEntriesRow
		if err := rows.Scan(
			&i.AgentID,
			&i.Source,
			&i.Level,
			&i.Message,
			&i.Count,
			&i.FirstSeen,
			&i.LastSeen,
			&i.ReceivedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchLogEntries = `-- name: SearchLogEntries :many
SELECT agent_id, source, level, message, count, first_seen, last_seen, received_at
FROM log_entries
WHERE agent_id = $1
  AND received_at >= $2
  AND received_at < $3
  AND search_vec @@ plainto_tsquery('english', $4)
ORDER BY received_at DESC
LIMIT $5
`

type SearchLogEntriesParams struct {
	AgentID        uuid.UUID `json:"agent_id"`
	ReceivedAt     time.Time `json:"received_at"`
	ReceivedAt_2   time.Time `json:"received_at_2"`
	PlaintoTsquery string    `json:"plainto_tsquery"`
	Limit          int32     `json:"limit"`
}

type SearchLogEntriesRow struct {
	AgentID    uuid.UUID `json:"agent_id"`
	Source     string    `json:"source"`
	Level      string    `json:"level"`
	Message    string    `json:"message"`
	Count      int32     `json:"count"`
	FirstSeen  time.Time `json:"first_seen"`
	LastSeen   time.Time `json:"last_seen"`
	ReceivedAt time.Time `json:"received_at"`
}

func (q *Queries) SearchLogEntries(ctx context.Context, arg SearchLogEntriesParams) ([]SearchLogEntriesRow, error) {
	rows, err := q.db.Query(ctx, searchLogEntries,
		arg.AgentID,
		arg.ReceivedAt,
		arg.ReceivedAt_2,
		arg.PlaintoTsquery,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SearchLogEntriesRow
	for rows.Next() {
		var i SearchLogEntriesRow
		if err := rows.Scan(
			&i.AgentID,
			&i.Source,
			&i.Level,
			&i.Message,
			&i.Count,
			&i.FirstSeen,
			&i.LastSeen,
			&i.ReceivedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
