// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: metrics.sql

package dbsqlc

import (
	"context"
	"time"

	"github.com/google/uuid"
)

type IngestMetricPointsParams struct {
	AgentID    uuid.UUID `json:"agent_id"`
	MetricName string    `json:"metric_name"`
	Value      float64   `json:"value"`
	Labels     []byte    `json:"labels"`
	RecordedAt time.Time `json:"recorded_at"`
}

const listMetricNames = `-- name: ListMetricNames :many
SELECT DISTINCT metric_name
FROM metric_points
WHERE agent_id = $1
ORDER BY metric_name
`

func (q *Queries) ListMetricNames(ctx context.Context, agentID uuid.UUID) ([]string, error) {
	rows, err := q.db.Query(ctx, listMetricNames, agentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var metric_name string
		if err := rows.Scan(&metric_name); err != nil {
			return nil, err
		}
		items = append(items, metric_name)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const queryMetricPoints = `-- name: QueryMetricPoints :many
SELECT agent_id, metric_name, value, labels, recorded_at, received_at
FROM metric_points
WHERE agent_id = $1
  AND metric_name = $2
  AND recorded_at >= $3
  AND recorded_at < $4
ORDER BY recorded_at DESC
LIMIT $5
`

type QueryMetricPointsParams struct {
	AgentID      uuid.UUID `json:"agent_id"`
	MetricName   string    `json:"metric_name"`
	RecordedAt   time.Time `json:"recorded_at"`
	RecordedAt_2 time.Time `json:"recorded_at_2"`
	Limit        int32     `json:"limit"`
}

func (q *Queries) QueryMetricPoints(ctx context.Context, arg QueryMetricPointsParams) ([]MetricPoint, error) {
	rows, err := q.db.Query(ctx, queryMetricPoints,
		arg.AgentID,
		arg.MetricName,
		arg.RecordedAt,
		arg.RecordedAt_2,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MetricPoint
	for rows.Next() {
		var i MetricPoint
		if err := rows.Scan(
			&i.AgentID,
			&i.MetricName,
			&i.Value,
			&i.Labels,
			&i.RecordedAt,
			&i.ReceivedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
