// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package dbsqlc

import (
	"database/sql/driver"
	"fmt"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type AlertEventStatus string

const (
	AlertEventStatusFiring   AlertEventStatus = "firing"
	AlertEventStatusResolved AlertEventStatus = "resolved"
)

func (e *AlertEventStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = AlertEventStatus(s)
	case string:
		*e = AlertEventStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for AlertEventStatus: %T", src)
	}
	return nil
}

type NullAlertEventStatus struct {
	AlertEventStatus AlertEventStatus `json:"alert_event_status"`
	Valid            bool             `json:"valid"` // Valid is true if AlertEventStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullAlertEventStatus) Scan(value interface{}) error {
	if value == nil {
		ns.AlertEventStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.AlertEventStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullAlertEventStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.AlertEventStatus), nil
}

type AlertSeverity string

const (
	AlertSeverityInfo     AlertSeverity = "info"
	AlertSeverityWarning  AlertSeverity = "warning"
	AlertSeverityCritical AlertSeverity = "critical"
)

func (e *AlertSeverity) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = AlertSeverity(s)
	case string:
		*e = AlertSeverity(s)
	default:
		return fmt.Errorf("unsupported scan type for AlertSeverity: %T", src)
	}
	return nil
}

type NullAlertSeverity struct {
	AlertSeverity AlertSeverity `json:"alert_severity"`
	Valid         bool          `json:"valid"` // Valid is true if AlertSeverity is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullAlertSeverity) Scan(value interface{}) error {
	if value == nil {
		ns.AlertSeverity, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.AlertSeverity.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullAlertSeverity) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.AlertSeverity), nil
}

type AlertTarget string

const (
	AlertTargetMetric     AlertTarget = "metric"
	AlertTargetLogPattern AlertTarget = "log_pattern"
	AlertTargetHeartbeat  AlertTarget = "heartbeat"
	AlertTargetSecurity   AlertTarget = "security"
)

func (e *AlertTarget) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = AlertTarget(s)
	case string:
		*e = AlertTarget(s)
	default:
		return fmt.Errorf("unsupported scan type for AlertTarget: %T", src)
	}
	return nil
}

type NullAlertTarget struct {
	AlertTarget AlertTarget `json:"alert_target"`
	Valid       bool        `json:"valid"` // Valid is true if AlertTarget is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullAlertTarget) Scan(value interface{}) error {
	if value == nil {
		ns.AlertTarget, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.AlertTarget.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullAlertTarget) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.AlertTarget), nil
}

type SubscriptionStatus string

const (
	SubscriptionStatusTrialing SubscriptionStatus = "trialing"
	SubscriptionStatusActive   SubscriptionStatus = "active"
	SubscriptionStatusPastDue  SubscriptionStatus = "past_due"
	SubscriptionStatusUnpaid   SubscriptionStatus = "unpaid"
	SubscriptionStatusCanceled SubscriptionStatus = "canceled"
)

func (e *SubscriptionStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = SubscriptionStatus(s)
	case string:
		*e = SubscriptionStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for SubscriptionStatus: %T", src)
	}
	return nil
}

type NullSubscriptionStatus struct {
	SubscriptionStatus SubscriptionStatus `json:"subscription_status"`
	Valid              bool               `json:"valid"` // Valid is true if SubscriptionStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullSubscriptionStatus) Scan(value interface{}) error {
	if value == nil {
		ns.SubscriptionStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.SubscriptionStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullSubscriptionStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.SubscriptionStatus), nil
}

type Agent struct {
	ID               uuid.UUID   `json:"id"`
	OrgID            uuid.UUID   `json:"org_id"`
	Name             string      `json:"name"`
	Hostname         string      `json:"hostname"`
	Tags             []byte      `json:"tags"`
	TokenHash        string      `json:"token_hash"`
	SigningKeyHash   string      `json:"signing_key_hash"`
	FingerprintHash  *string     `json:"fingerprint_hash"`
	FingerprintDrift bool        `json:"fingerprint_drift"`
	Frozen           bool        `json:"frozen"`
	RotationRequired bool        `json:"rotation_required"`
	ExpiresAt        time.Time   `json:"expires_at"`
	Revoked          bool        `json:"revoked"`
	LastSeenAt       **time.Time `json:"last_seen_at"`
	CreatedAt        time.Time   `json:"created_at"`
}

type AlertEvent struct {
	ID          uuid.UUID        `json:"id"`
	RuleID      uuid.UUID        `json:"rule_id"`
	AgentID     uuid.UUID        `json:"agent_id"`
	FiredAt     time.Time        `json:"fired_at"`
	ResolvedAt  **time.Time      `json:"resolved_at"`
	ValueAtFire []byte           `json:"value_at_fire"`
	Status      AlertEventStatus `json:"status"`
}

type AlertRule struct {
	ID                   uuid.UUID       `json:"id"`
	OrgID                uuid.UUID       `json:"org_id"`
	Name                 string          `json:"name"`
	Target               AlertTarget     `json:"target"`
	Condition            []byte          `json:"condition"`
	Severity             AlertSeverity   `json:"severity"`
	NotificationChannels []byte          `json:"notification_channels"`
	EscalateAfter        pgtype.Interval `json:"escalate_after"`
	EscalateTo           []byte          `json:"escalate_to"`
	Enabled              bool            `json:"enabled"`
	CreatedAt            time.Time       `json:"created_at"`
	UpdatedAt            time.Time       `json:"updated_at"`
}

type LogEntriesDefault struct {
	AgentID    uuid.UUID   `json:"agent_id"`
	Source     string      `json:"source"`
	Level      string      `json:"level"`
	Message    string      `json:"message"`
	Count      int32       `json:"count"`
	FirstSeen  time.Time   `json:"first_seen"`
	LastSeen   time.Time   `json:"last_seen"`
	ReceivedAt time.Time   `json:"received_at"`
	SearchVec  interface{} `json:"search_vec"`
}

type LogEntry struct {
	AgentID    uuid.UUID   `json:"agent_id"`
	Source     string      `json:"source"`
	Level      string      `json:"level"`
	Message    string      `json:"message"`
	Count      int32       `json:"count"`
	FirstSeen  time.Time   `json:"first_seen"`
	LastSeen   time.Time   `json:"last_seen"`
	ReceivedAt time.Time   `json:"received_at"`
	SearchVec  interface{} `json:"search_vec"`
}

type MetricPoint struct {
	AgentID    uuid.UUID `json:"agent_id"`
	MetricName string    `json:"metric_name"`
	Value      float64   `json:"value"`
	Labels     []byte    `json:"labels"`
	RecordedAt time.Time `json:"recorded_at"`
	ReceivedAt time.Time `json:"received_at"`
}

type MetricPointsDefault struct {
	AgentID    uuid.UUID `json:"agent_id"`
	MetricName string    `json:"metric_name"`
	Value      float64   `json:"value"`
	Labels     []byte    `json:"labels"`
	RecordedAt time.Time `json:"recorded_at"`
	ReceivedAt time.Time `json:"received_at"`
}

type Organization struct {
	ID                   uuid.UUID          `json:"id"`
	Name                 string             `json:"name"`
	Slug                 string             `json:"slug"`
	OwnerID              uuid.UUID          `json:"owner_id"`
	StripeCustomerID     *string            `json:"stripe_customer_id"`
	StripeSubscriptionID *string            `json:"stripe_subscription_id"`
	SubscriptionStatus   SubscriptionStatus `json:"subscription_status"`
	TrialEndsAt          time.Time          `json:"trial_ends_at"`
	CreatedAt            time.Time          `json:"created_at"`
	UpdatedAt            time.Time          `json:"updated_at"`
}

type User struct {
	ID           uuid.UUID `json:"id"`
	Email        string    `json:"email"`
	Name         string    `json:"name"`
	PasswordHash string    `json:"password_hash"`
	CreatedAt    time.Time `json:"created_at"`
	UpdatedAt    time.Time `json:"updated_at"`
}
