// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package dbsqlc

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	CreateOrganization(ctx context.Context, arg CreateOrganizationParams) (CreateOrganizationRow, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (CreateUserRow, error)
	GetOrganizationByOwnerID(ctx context.Context, ownerID uuid.UUID) (GetOrganizationByOwnerIDRow, error)
	GetUserByID(ctx context.Context, id uuid.UUID) (GetUserByIDRow, error)
	// Returns password_hash so the service can verify it. Not used anywhere else.
	GetUserForLogin(ctx context.Context, email string) (GetUserForLoginRow, error)
}

var _ Querier = (*Queries)(nil)
