// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: users.sql

package dbsqlc

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createOrganization = `-- name: CreateOrganization :one
INSERT INTO organizations (name, slug, owner_id)
VALUES ($1, $2, $3)
RETURNING id, name, slug, owner_id, subscription_status, trial_ends_at, created_at
`

type CreateOrganizationParams struct {
	Name    string    `json:"name"`
	Slug    string    `json:"slug"`
	OwnerID uuid.UUID `json:"owner_id"`
}

type CreateOrganizationRow struct {
	ID                 uuid.UUID          `json:"id"`
	Name               string             `json:"name"`
	Slug               string             `json:"slug"`
	OwnerID            uuid.UUID          `json:"owner_id"`
	SubscriptionStatus SubscriptionStatus `json:"subscription_status"`
	TrialEndsAt        time.Time          `json:"trial_ends_at"`
	CreatedAt          time.Time          `json:"created_at"`
}

func (q *Queries) CreateOrganization(ctx context.Context, arg CreateOrganizationParams) (CreateOrganizationRow, error) {
	row := q.db.QueryRow(ctx, createOrganization, arg.Name, arg.Slug, arg.OwnerID)
	var i CreateOrganizationRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.OwnerID,
		&i.SubscriptionStatus,
		&i.TrialEndsAt,
		&i.CreatedAt,
	)
	return i, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (email, name, password_hash)
VALUES ($1, $2, $3)
RETURNING id, email, name, created_at
`

type CreateUserParams struct {
	Email        string `json:"email"`
	Name         string `json:"name"`
	PasswordHash string `json:"password_hash"`
}

type CreateUserRow struct {
	ID        uuid.UUID `json:"id"`
	Email     string    `json:"email"`
	Name      string    `json:"name"`
	CreatedAt time.Time `json:"created_at"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (CreateUserRow, error) {
	row := q.db.QueryRow(ctx, createUser, arg.Email, arg.Name, arg.PasswordHash)
	var i CreateUserRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.CreatedAt,
	)
	return i, err
}

const getOrganizationByOwnerID = `-- name: GetOrganizationByOwnerID :one
SELECT id, name, slug, owner_id, subscription_status, stripe_customer_id, stripe_subscription_id
FROM organizations
WHERE owner_id = $1
LIMIT 1
`

type GetOrganizationByOwnerIDRow struct {
	ID                   uuid.UUID          `json:"id"`
	Name                 string             `json:"name"`
	Slug                 string             `json:"slug"`
	OwnerID              uuid.UUID          `json:"owner_id"`
	SubscriptionStatus   SubscriptionStatus `json:"subscription_status"`
	StripeCustomerID     *string            `json:"stripe_customer_id"`
	StripeSubscriptionID *string            `json:"stripe_subscription_id"`
}

func (q *Queries) GetOrganizationByOwnerID(ctx context.Context, ownerID uuid.UUID) (GetOrganizationByOwnerIDRow, error) {
	row := q.db.QueryRow(ctx, getOrganizationByOwnerID, ownerID)
	var i GetOrganizationByOwnerIDRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.OwnerID,
		&i.SubscriptionStatus,
		&i.StripeCustomerID,
		&i.StripeSubscriptionID,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, email, name, created_at
FROM users
WHERE id = $1
LIMIT 1
`

type GetUserByIDRow struct {
	ID        uuid.UUID `json:"id"`
	Email     string    `json:"email"`
	Name      string    `json:"name"`
	CreatedAt time.Time `json:"created_at"`
}

func (q *Queries) GetUserByID(ctx context.Context, id uuid.UUID) (GetUserByIDRow, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i GetUserByIDRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.CreatedAt,
	)
	return i, err
}

const getUserForLogin = `-- name: GetUserForLogin :one
SELECT id, email, name, password_hash
FROM users
WHERE email = $1
LIMIT 1
`

type GetUserForLoginRow struct {
	ID           uuid.UUID `json:"id"`
	Email        string    `json:"email"`
	Name         string    `json:"name"`
	PasswordHash string    `json:"password_hash"`
}

// Returns password_hash so the service can verify it. Not used anywhere else.
func (q *Queries) GetUserForLogin(ctx context.Context, email string) (GetUserForLoginRow, error) {
	row := q.db.QueryRow(ctx, getUserForLogin, email)
	var i GetUserForLoginRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.PasswordHash,
	)
	return i, err
}
